/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dados.Cliente;
import dados.Funcionario;
import dados.Pedido;
import dados.Produto;
import dados.Venda;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import repositorio.RepositorioClientes;
import repositorio.RepositorioFuncionarios;
import repositorio.RepositorioVendas;
import repositorio.ListaPedidos;
import tabelas.PedidosTableModel;
import repositorio.RepositorioProdutos;

/**
 *
 * @author Walison Filipe
 */
public class TelaVenda extends javax.swing.JFrame {

    PedidosTableModel carrinhoTabela;

    //globais para troca de informaçoes entre os metodos e campos 
    Produto p;
    Cliente c;
    Funcionario f;

    /**
     * Creates new form TelaVenda
     */
    public TelaVenda() {
        initComponents();

        carrinhoTabela = new PedidosTableModel();
        jTablePedido.setModel(carrinhoTabela);

        //iniicando componentes desativados 
        jTNomeCliente.setEditable(false);
        jTNomeProduto.setEditable(false);
        jTValorUnit.setEditable(false);
        jTNomeVendedor.setEditable(false);
        jTQuantTotal.setEditable(false);
        jTTotal.setEditable(false);
        jTItens.setEditable(false);
        jTValorTotal.setEditable(false);
        jTDesconto.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jTCpf = new javax.swing.JFormattedTextField();
        jBBuscarCliente = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTNomeCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTCodigoProduto = new javax.swing.JTextField();
        jBBuscarProduto = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTNomeProduto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTQuantidadeProdutos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTValorTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTValorUnit = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePedido = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jTItens = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTQuantTotal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTDesconto = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTCodigoVendedor = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTNomeVendedor = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTTotal = new javax.swing.JTextField();

        jMenu1.setText("jMenu1");

        jScrollPane1.setViewportView(jEditorPane1);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vendas");
        setResizable(false);

        jLabel1.setText("CPF:");

        try {
            jTCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTCpf.setPreferredSize(new java.awt.Dimension(100, 20));

        jBBuscarCliente.setText("Buscar");
        jBBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarClienteActionPerformed(evt);
            }
        });

        jButton1.setText("Cancelar ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome do cliente:");

        jTNomeCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTNomeCliente.setForeground(new java.awt.Color(255, 0, 0));

        jLabel3.setText("Cód. produto:");

        jBBuscarProduto.setText("Buscar");
        jBBuscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarProdutoActionPerformed(evt);
            }
        });

        jLabel4.setText("Produto:");

        jLabel5.setText("Quant.:");

        jTQuantidadeProdutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTQuantidadeProdutosKeyPressed(evt);
            }
        });

        jLabel6.setText("Desconto:");

        jTValorTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTValorTotal.setForeground(new java.awt.Color(255, 0, 0));

        jLabel7.setText("Valor unit.:");

        jTValorUnit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTValorUnitKeyPressed(evt);
            }
        });

        jLabel9.setText("Forma de pagamento:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        this.jComboBox1.removeAllItems();
        this.jComboBox1.setSelectedIndex(-1);

        jTablePedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTablePedido);

        jLabel10.setText("Itens:");

        jLabel11.setText("Quant. total:");

        jTQuantTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTQuantTotalActionPerformed(evt);
            }
        });

        jLabel12.setText("Valor com desconto:");

        jTDesconto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTDesconto.setForeground(new java.awt.Color(0, 0, 255));

        jButton2.setText("Adicionar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel13.setText("Cód. ");

        jButton4.setText("Remover");
        jButton4.setToolTipText("Selecione um produto na lista para remover");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("buscar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel8.setText("Nome do Vendedor:");

        jButton9.setText("Finalizar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel15.setText("Valor:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBBuscarCliente)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTValorTotal)
                                    .addComponent(jTDesconto)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTItens, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTQuantTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jTTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jBBuscarProduto))
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel4)
                                                        .addGap(225, 225, 225)
                                                        .addComponent(jLabel5))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jTNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jTQuantidadeProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jTValorUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jButton2)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButton4)))))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTCodigoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jTNomeVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 348, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNomeVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6)
                    .addComponent(jTCodigoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscarCliente)
                    .addComponent(jTNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBBuscarProduto)
                            .addComponent(jTNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTQuantidadeProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTValorUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addComponent(jButton4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTQuantTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton9)
                    .addComponent(jTTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        this.jComboBox1.addItem("Dinheiro");
        this.jComboBox1.addItem("Cartão de crédito");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //limpar a lista de pedidos 
        ListaPedidos.limparCarrinho();

        limparCampos();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarClienteActionPerformed

        if (!RepositorioClientes.listaClientes.isEmpty()) {

            String cpf = jTCpf.getText();

            if (!"   .   .   -  ".equals(cpf)) {
                Cliente _c = RepositorioClientes.pesquisarClienteCpf(cpf);

                if (_c != null) {
                    //passa os dados do cliente para a global 
                    this.c = _c;
                    jTNomeCliente.setText(_c.getNome());

                } else {
                    JOptionPane.showMessageDialog(this, "Cliente não cadastrado");
                    jTCpf.setText(null);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Informe o cpf do cliente!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "O sistema não possui clientes cadastrados!");
        }

    }//GEN-LAST:event_jBBuscarClienteActionPerformed

    private void jBBuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarProdutoActionPerformed

        if (!"".equals(jTCodigoProduto.getText())) {

            int codProduto = Integer.parseInt(jTCodigoProduto.getText());

            if (codProduto != 0) {
                Produto _p = RepositorioProdutos.pesquisarProdutoCod(codProduto);

                if (_p != null) {
                    //passa os dados do produto para a global 
                    this.p = _p;
                    //seta os campos 
                    jTNomeProduto.setText(_p.getNome());
                    jTValorUnit.setText(String.valueOf(_p.getPrecoVenda()));
                } else {
                    JOptionPane.showMessageDialog(this, "Produto não cadastrado");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Informe o código do produto");
        }
    }//GEN-LAST:event_jBBuscarProdutoActionPerformed

    private void jTValorUnitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTValorUnitKeyPressed

    }//GEN-LAST:event_jTValorUnitKeyPressed

    private void jTQuantidadeProdutosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTQuantidadeProdutosKeyPressed

    }//GEN-LAST:event_jTQuantidadeProdutosKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //logica para realizar o pedido e exibir os dados na tabela 
        if (jTNomeProduto.getText() != null) {

            if (!"".equals(jTQuantidadeProdutos.getText())) {

                //coletando e armazenando dados 
                String nomeProduto = this.p.getNome();
                int codProduto = this.p.getCodigo();
                double precoProduto = this.p.getPrecoVenda();
                double quantProdutos = Double.parseDouble(jTQuantidadeProdutos.getText());
                double subTotal = (quantProdutos * precoProduto);

                //criando um pedido
                Pedido _pedido = new Pedido(codProduto, nomeProduto, quantProdutos, precoProduto, subTotal);
                carrinhoTabela.atualizarTabela();

                //adiciona o Pedido no ArrayList
                ListaPedidos.addPedido(_pedido);

                if (quantProdutos <= this.p.getQuantidade() && ListaPedidos.quantTotal() <= this.p.getQuantidade()) {

                    //itens
                    String itens = Double.parseDouble(ListaPedidos.carrinhoCompras.size() + "") + "";  //gambiarra huehuehuehu
                    jTItens.setText(itens);

                    //quantidadeTotal
                    String quantTotal = ListaPedidos.quantTotal() + "";
                    jTQuantTotal.setText(quantTotal);

                    //Total
                    String total = ListaPedidos.valorTotal() + "";
                    jTTotal.setText(total);

                    //limpar campos
                    jTNomeProduto.setText(null);
                    jTQuantidadeProdutos.setText(null);
                    jTCodigoProduto.setText(null);
                    jTValorUnit.setText(null);

                    //teste
                    System.out.print(p);
                } else {

                    JOptionPane.showMessageDialog(this, "O produto não possui estoque suficiente para atender o pedido");
                    ListaPedidos.carrinhoCompras.remove(_pedido);
                    carrinhoTabela.atualizarTabela();
                }
            } else if ("".equals(jTQuantidadeProdutos.getText())) {
                JOptionPane.showMessageDialog(this, "Informe a quantidade");
            }
        } else if ("".equals(jTCodigoProduto.getText())) {
            JOptionPane.showMessageDialog(this, "Informe o código do produto");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //verifica se o ArrayList de funcionarios esta vazio 

        if (!"".equals(jTCodigoVendedor.getText())) {

            int codigoVendedor = Integer.parseInt(jTCodigoVendedor.getText());

            Funcionario _f = RepositorioFuncionarios.pesquisarFuncionarioCodigo(codigoVendedor);

            if (_f != null) {
                //atribuindo para o global
                this.f = _f;
                jTNomeVendedor.setText(_f.getNome());
            } else {
                JOptionPane.showMessageDialog(this, "Funcionário não cadastrado/existente!");
                jTCodigoVendedor.setText(null);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Insira o código do funcionário");
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Pedido _pedido = carrinhoTabela.getPedido(jTablePedido.getSelectedRow());

        //se nenhuma linha da tabela estiver selecionada (getSelectedRow = -1) o Pedido retorna vazio
        if (_pedido != null) {
            ListaPedidos.removerPedido(_pedido);
            carrinhoTabela.atualizarTabela();

            //atualizando campos da interface
            String itens = Double.parseDouble(ListaPedidos.carrinhoCompras.size() + "") + ""; //gambiarra ON! 
            jTItens.setText(itens);

            //coleta o valor atual da variavel e calcula o pedido retirado
            String qT = Double.parseDouble(jTQuantTotal.getText()) - _pedido.getQuantProdutos() + "";
            jTQuantTotal.setText(qT);

            String total = Double.parseDouble(jTTotal.getText()) - _pedido.getSubTotal() + "";
            jTTotal.setText(total);

        } else {
            JOptionPane.showMessageDialog(this, "Selecione na lista o produto que deseja remover");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    //metodo para pegar data do sistema
    private String getData() {

        Date data = new Date(System.currentTimeMillis());
        SimpleDateFormat formatarDate = new SimpleDateFormat("dd/MM/yyyy");
        return (formatarDate.format(data));
    }

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        if (validarCampos() == true) {

            if (!"".equals(jTDesconto.getText()) && !"".equals(jTValorTotal.getText())) {

                int opcao = JOptionPane.showConfirmDialog(this, "\nNome cliente: " + c.getNome() + "\nNome vendedor: " + f.getNome()+ "\nForma de pagamento: "+jComboBox1.getSelectedItem() + "\nTotal: " + jTTotal.getText()+"\n", "Os dados estão corretos? ", JOptionPane.YES_NO_OPTION);

                if (opcao == JOptionPane.YES_OPTION) {

                    String nomeCliente = this.c.getNome();
                    String nomeVendedor = this.f.getNome();
                    //faz uma copia do arrayList contendo o pedido do cliente
                    ArrayList<Pedido> pedido = new ArrayList(ListaPedidos.carrinhoCompras);
                    String dataCompra = getData();
                    String formaPagamento = jComboBox1.getSelectedItem() + "";
                    double desconto = Double.parseDouble(jTDesconto.getText());
                    double total = Double.parseDouble(jTTotal.getText());

                    //criar um objeto venda 
                    Venda v = new Venda(dataCompra, formaPagamento, total, desconto, nomeCliente, nomeVendedor, pedido);

                    //adiciona uma venda ao ArrayList 
                    RepositorioVendas.addVenda(v);

                    //mensagem confirmacao, falta editar
                    JOptionPane.showMessageDialog(this, "Venda concluída!");

                    //apagando o arrayList inteiro para receber pedidos de outros clientes 
                    ListaPedidos.carrinhoCompras.clear();

                    //teste
                    System.out.print(ListaPedidos.carrinhoCompras.size());

                    //limpar campos 
                    limparCampos();

                    //atualizar estoque dos produtos comprados 
                    RepositorioProdutos.atualizarEstoque(pedido);

                    //fechar a tela 
                    this.dispose();

                } else if (opcao == JOptionPane.NO_OPTION) {

                    JOptionPane.showMessageDialog(this, "Venda cancelada");

                    limparCampos();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Escolha uma forma de pagamento");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Campo(s) em branco!");
        }

    }//GEN-LAST:event_jButton9ActionPerformed

    private void limparCampos() {

        jTCodigoProduto.setText(null);
        jTCodigoVendedor.setText(null);
        jTCpf.setText(null);
        jTDesconto.setText(null);
        jTItens.setText(null);
        jTNomeCliente.setText(null);
        jTNomeProduto.setText(null);
        jTNomeVendedor.setText(null);
        jTQuantTotal.setText(null);
        jTQuantidadeProdutos.setText(null);
        jTTotal.setText(null);
        jTValorTotal.setText(null);
        jTValorUnit.setText(null);
    }


    private void jTQuantTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTQuantTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTQuantTotalActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (!ListaPedidos.carrinhoCompras.isEmpty()) {

            if (jComboBox1.getSelectedIndex() == 0) {
                double v = ListaPedidos.valorTotal() * 0.01;
                jTDesconto.setText(v + "");
                double vT = ListaPedidos.valorTotal() - v;
                jTValorTotal.setText(vT + "");
            } else if (jComboBox1.getSelectedIndex() == 1) {
                jTDesconto.setText(0.0 + "");
                double vT = ListaPedidos.valorTotal();
                jTValorTotal.setText(vT + "");
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private boolean validarCampos() {

        boolean camposValidos = false;
        if (!"".equals(jTNomeCliente.getText()) && !"".equals(jTNomeVendedor.getText()) && !ListaPedidos.carrinhoCompras.isEmpty()) {
            camposValidos = true;
        }
        return camposValidos;
    }

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged

    }//GEN-LAST:event_jComboBox1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscarCliente;
    private javax.swing.JButton jBBuscarProduto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTCodigoProduto;
    private javax.swing.JTextField jTCodigoVendedor;
    private javax.swing.JFormattedTextField jTCpf;
    private javax.swing.JTextField jTDesconto;
    private javax.swing.JTextField jTItens;
    private javax.swing.JTextField jTNomeCliente;
    private javax.swing.JTextField jTNomeProduto;
    private javax.swing.JTextField jTNomeVendedor;
    private javax.swing.JTextField jTQuantTotal;
    private javax.swing.JTextField jTQuantidadeProdutos;
    private javax.swing.JTextField jTTotal;
    private javax.swing.JTextField jTValorTotal;
    private javax.swing.JTextField jTValorUnit;
    private javax.swing.JTable jTablePedido;
    // End of variables declaration//GEN-END:variables
}
